---
title: "Data Visualization and Interaction"
author: "Zihui Wang"
date: "2022-10-12"
output:
  html_document: default
---

```{r, include=F}
library(plotly)
library(dplyr)
library(maps)
```

Data Visualization and Interaction for US crime rates data in 1973 ("USArrests" in R datasets)  
Better knit to HTML or run in Rmarkdown for the interaction function  

```{r}
#Import data set describing violent crime rates by US state
USArrest<-USArrests

#Vector of codes of states
Code_States<-c("AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT","VA","WA","WV","WI","WY")

#Get total crime rates
Total<-with(USArrest, Murder+Assault+Rape)
state<-row.names(USArrest)
USArrest<-cbind.data.frame(state,USArrest,Code_States,Total)
```

```{r}
#Information for interaction; When you put your cursor on a state, you can see the basic information of crime rates in this area
USArrest$hover <- with(USArrest, paste(state, '<br>', "Murder:", Murder,"<br>","Assault:", Assault, "<br>","Rape:",Rape,"<br>","Total:",Total,"<br>","Urban Population:",UrbanPop,"%","<br>"))
```

```{r}
#Connect the data to US map
fig <- plot_geo(USArrest, locationmode = 'USA-states')

#Plot
fig <- fig %>% add_trace(
  locations = ~Code_States,
  type='choropleth',
  z= ~Total,
  text = ~hover,
  color=~Total,
  colors = 'Greys'
)

#Title
fig <- fig %>% layout(
  title = 'Crime Rates by US State (Total)'
)

#Show
fig
```

