---
title: "Line Search-Fixed, Backtracking and Exact"
author: "Zihui Wang"
date: "2022-10-13"
output: 
  pdf_document: default
---

```{r}
#Fixed Line Search
Fixed<-function(alpha0,delta_f1,delta_f2,x0,itr,epsilon){
  x=x0
  alpha=alpha0
  x.values=matrix(0,itr+1,2)
  x.values[1,]=x
  for(t in 1:itr){
    x=x-alpha*c(delta_f1(x[1]),delta_f2(x[2]))
    x.values[t+1,]=x
    if(norm(alpha*c(delta_f1(x[1]),delta_f2(x[2])),type="2")<=epsilon) break
  }
  return(list(x=x,x.values=x.values))
}
```
  
```{r}
#Backtracking Line Search
Backtracking<-function(alpha0,delta_f1,delta_f2,f,x0,itr,epsilon){
  x=x0
  alpha=alpha0
  x.values=matrix(0,itr+1,2)
  x.values[1,]=x
  for(t in 1:itr){
    x_before=x
    x=x-alpha*c(delta_f1(x[1]),delta_f2(x[2]))
    x.values[t+1,]=x
    if(f(x)>f(x_before)){
      alpha=alpha/2
    }
    if(norm(alpha*c(delta_f1(x[1]),delta_f2(x[2])),type="2")<=epsilon) break
  }
  return(list(x=x,x.values=x.values))
}
```
  
```{r}
#Exact Line Search
Exactline<-function(x0,itr,epsilon){
  x=x0
  x.values=matrix(0,itr+1,2)
  x.values[1,]=x
  for(t in 1:itr){
    x_before=x
    alpha=(100*x[1]^2-x[2]^2)/(1000*x[1]^2-x[2]^2)
    x=x-alpha*c(10*x[1],x[2])
    
    x.values[t+1,]=x
    if(norm(alpha*c(delta_f1(x[1]),delta_f2(x[2])),type="2")<=epsilon) break
  }
  return(list(x=x,x.values=x.values))
}
```

```{r}
#Test
#The function
f<-function(x){(10*x[1]^2+x[2]^2)/2}
delta_f1<-function(x){10*x}
delta_f2<-function(x){x}
```

```{r}
#Get result (Fixed)
x<-Fixed(0.12,delta_f1,delta_f2,c(1,1),40,10^(-6))[[1]]
x.values<-Fixed(0.12,delta_f1,delta_f2,c(1,1),40,10^(-6))[[2]]

#Contour plot (Fixed)
paste("x1=",x[1],", x2=",x[2])
z = matrix(0,100,100)
x1.max = max(1,ceiling(max(x.values[,1])))
x1.min = min(-0.1,floor(min(x.values[,1])))
x2.max = max(1,ceiling(max(x.values[,2])))
x2.min = min(-0.1,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:40){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```

```{r}
#Get result (Backtracking)
x<-Backtracking(0.25,delta_f1,delta_f2,f,c(1,1),40,10^(-6))[[1]]
x.values<-Backtracking(0.25,delta_f1,delta_f2,f,c(1,1),40,10^(-6))[[2]]

#Contour plot
paste("x1=",x[1],", x2=",x[2])
z = matrix(0,100,100)
x1.max = max(1,ceiling(max(x.values[,1])))
x1.min = min(-0.1,floor(min(x.values[,1])))
x2.max = max(1,ceiling(max(x.values[,2])))
x2.min = min(-0.1,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:40){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```

```{r}
#Get result (Exact)
x<-Exactline(c(1,1),40,10^(-6))[[1]]
x.values<-Exactline(c(1,1),40,10^(-6))[[2]]

#Contour plot
paste("x1=",x[1],", x2=",x[2])
z = matrix(0,100,100)
x1.max = max(1,ceiling(max(x.values[,1])))
x1.min = min(-0.1,floor(min(x.values[,1])))
x2.max = max(1,ceiling(max(x.values[,2])))
x2.min = min(-0.1,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:40){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```