---
title: "Brent's Root-Finding Algorithm"
author: "Zihui Wang"
date: "2022-10-12"
output: 
  pdf_document: default
---

```{r}
fzerotx<-function(F,ab,tol){
  
  a = ab[1]
  b = ab[2]
  fa = F(a)
  fb = F(b)

  if(sign(fa) == sign(fb)){
    print("Function must change sign on the interval")
    break;
  }
  
  c = a
  fc = fa
  d = b - c
  e = d;
  
  while(fb != 0){
    if(sign(fa) == sign(fb)){
      a = c
      fa = fc
      d = b - c
      e = d
    }
    
    if(abs(fa) < abs(fb)){
      c = b
      b = a
      a = c
      fc = fb
      fb = fa
      fa = fc
    }

    m = 0.5*(a - b)
    
    if(abs(m) <= tol | fb == 0){
      break;
    }

    if(abs(e) < tol | abs(fc) <= abs(fb)){
      #Bisection method part
      d = m
      e = m
    }
    
    else{
      #Interpolation method part
      s = fb/fc
      
      if(a == c){
        #Linear interpolation (secant) part
         p = 2.0*m*s
         q = 1.0 - s
      }
      else{
         #Inverse quadratic interpolation part
         q = fc/fa
         r = fb/fa
         p = s*(2.0*m*q*(q - r) - (b - c)*(r - 1.0))
         q = (q - 1.0)*(r - 1.0)*(s - 1.0)
      }
      
      if(p > 0){
        q = -q
      }
      else{
        p = -p
      }
      
      #If interpolated point is acceptable
      if((2.0*p < 3.0*m*q - abs(tol*q)) & (p < abs(0.5*e*q))){
         e = d
         d = p/q
      }
      else{
         d = m
         e = m
      }
   }
      
   #Next point
   c = b
   fc = fb
   
   if(abs(d) > tol){
     b = b + d
   }
   else{
     b = b - sign(b-a)*tol
   }
 }
  return(b)
}
```

```{r}
#Test
G<-function(x){x^2-1}
fzerotx(G,c(0,1),10^(-6))
```
