---
title: "Direct Search Methods"
author: "Zihui Wang"
date: "2022-10-12"
output: pdf_document
---

*Two basic algorithms: Golden Ratio Method and Fibonacci Method:*  
```{r}
#Golden Ratio
GR<-function(f,epsilon,lower,upper){
  num_iteration<-0
  num_function<-1
  r<-(sqrt(5)-1)/2
  
  while(abs(upper-lower)>epsilon){
    
    lower_backup<-upper-r*(upper-lower)
    upper_backup<-lower+r*(upper-lower)
    
    if(f(upper_backup)>=f(lower_backup)){
      upper<-upper_backup
    }
    else{
      lower<-lower_backup
    }
    num_iteration<-num_iteration+1
    num_function<-num_function+1
  }
  return(list("Golden Ratio",
              "minimizer:",(upper+lower)/2,
              "interations:",num_iteration,
              "functions:",num_function))
}
```
  
```{r}
#Fibonacci
FB<-function(f,epsilon,lower,upper){
   F = vector()
   F[1] = 1
   F[2] = 1
   n = 2
   while((upper-lower)/F[n]>epsilon){
     n = n+1
     F[n] = F[n-1]+F[n-2]
   }
  
  num_iteration<-0
  num_function<-1
  
  while(upper-lower>epsilon){
    
    lower_backup=upper-(upper-lower)*F[n-1]/F[n]
    upper_backup=lower+(upper-lower)*F[n-1]/F[n]
    
    if(f(lower_backup)>=f(upper_backup)){
      lower<-lower_backup
    }
    if(f(lower_backup)<f(upper_backup)){
      upper<-upper_backup
    }
    n<-n-1
    num_iteration<-num_iteration+1
    num_function<-num_function+1
  }
  return(list("Fibonacci",
              "minimizer:",(upper+lower)/2,
              "interations:",num_iteration,
              "functions:",num_function))
}
```
  
```{r}
#Test
h<-function(x){x^3/3-x^2/2-x-1}
GR(h,10^(-6),1,2)
FB(h,10^(-6),1,2)
```