---
title: "Gauss-Siedel Algorithm"
author: "Zihui Wang"
date: "2022-10-12"
output: 
  pdf_document: default
---

*Realization of Guass-Siedel Method solving system of linear equations:*   
```{r}
#For Ax=b
GSM<-function(A,b,initial,t){
  n<-nrow(A)
  x<-initial
  
  for(m in 1:t){
    
    x[1]
    for(i in 1:n){
      sum1<-0
      sum2<-0
      
      if(i==1){
        for(k in (i+1):n){
          sum2<-sum2+A[i,k]*x[k]
        }
        x[i]<-(b[i]-sum2)/A[i,i]
      }
      
      else{
        
        if(i==n){
          for(j in 1:(i-1)){
            sum1<-sum1+A[i,j]*x[j]
          }
          x[i]<-(b[i]-sum1)/A[i,i]
        }
        
        else{
          for(j in 1:(i-1)){
            sum1<-sum1+A[i,j]*x[j]
          }
          for(k in (i+1):n){
            sum2<-sum2+A[i,k]*x[k]
          }
          x[i]<-(b[i]-sum1-sum2)/A[i,i]
        }
      }
    }
  }
  return(x)
}
```
  
```{r}
#Try to solve a problem
A1<-matrix(c(2,-1,0,1,-3,1,-1,1,-3),byrow=T,ncol=3)
b1<-c(2,-2,-6)
x0<-c(0,0,0)
GSM(A1,b1,x0,20)
```