---
title: "Gauss Newton Method-LMF Algorithm"
author: "Zihui Wang"
date: "2022-10-13"
output: 
  pdf_document: default
---

*This is an improvement for Gauss-Newton Method for root-finding problem:*  
```{r}
#LMF Algorithm itself
LMF<-function(f,t,Nt,dr,dK,beta0,lambda0,itr,epsilon){
  betat=beta0
  lambdat<-lambda0
  xt <- Nt - f(t,betat[1],betat[2])
  Jt <- cbind(mapply(dr,t=t,r=betat[1],K=betat[2]),
              mapply(dK,t=t,r=betat[1],K=betat[2]))
  grad <- sum((t(xt) %*% Jt)^2)
  
  i=0
  while (i<=itr & grad>epsilon){
    Jt <- cbind(mapply(dr,t=t,r=betat[1],K=betat[2]),
                mapply(dK,t=t,r=betat[1],K=betat[2]))
    deltbeta<-solve(t(Jt) %*% Jt + lambdat*diag(2)) %*% t(Jt) %*% xt
    rout=(norm(betat,type="2")^2-norm(betat+deltbeta,type="2")^2)/(t(deltbeta) %*% (lambdat * deltbeta+t(Jt) %*% xt))
    grad <- sum((t(xt) %*% Jt)^2)
    
    if(rout<0.25){
      lambdat=4*lambdat
    }
    else if(rout>0.75){
      lambdat=0.5*lambdat
    }
    if(rout<=0){
      betat=betat
    }
    else{
      betat=betat+deltbeta
    }
    i=i+1
  }
  return(list(beta=betat))
}
```
  
```{r}
#Test
t <- c(0, 8, 28, 41, 63, 79, 97, 117, 135, 154)
Nt <- c(2, 47, 192, 256, 768, 896, 1120, 896, 1184, 1024)
N0 <- Nt[1]
f <- function(t,r,K){K*N0/(N0+(K-N0)*exp(-r*t))}
dr <- function(t,r,K){t*K*N0*(K-N0)*exp(-r*t)/(N0+(K-N0)*exp(-r*t))^2}
dK <- function(t,r,K){(N0)^2*(1-exp(-K*t))/(N0+(r-N0)*exp(-r*t))^2}
beta0<-c(0.1,1000)
lambda0<-1
LMF(f,t,Nt,dr,dK,beta0,lambda0,500,1e-20)
```