---
title: "Optimization-Newton, Gradient Descent and Conjugate Gradient"
author: "Zihui Wang"
date: "2022-10-13"
output: pdf_document
---

*These are 3 basic optimization algorithms:*  
*Newton's, Gradient Descent and Conjugate Gradient*  
```{r}
#Take a specific function f(x1, x2)=100*(1-x1)^2+(x2-x1^2)^2 as an example:
f<-function(x) (1-x[1])^2+100*(x[2]-x[1]^2)^2

#Newton
Newton<-function(x0,itr,epsilon){
  f_1<-function(x) c(2*(x[1]-1)+400*x[1]*(x[1]^2-x[2]),200*(x[2]-x[1]^2))
  f_2<-function(x) matrix(c(2+(1200*x[1]^2-400*x[2]),-400*x[1],-400*x[1],200),
                          ncol=2,byrow=T)
  x=x0
  x.values=matrix(0,nrow=itr+1,ncol=2)
  x.values[1,]=x0
  
  i=0
  for(t in 1:itr){
    x_before=x
    x=x-solve(f_2(x)) %*% f_1(x)
    x.values[t+1,]=x
    
    i=i+1
    
    if(norm(solve(f_2(x)) %*% f_1(x),type="2")<=epsilon) break
  }
  times=i
  x.values=x.values[1:(times+1),]
  return(list(x=x,x.values=x.values,times=times))
} 
```

```{r}
#Gradient Descend
Grad<-function(alpha0,x0,itr,epsilon){
  f<-function(x) (1-x[1])^2+100*(x[2]-x[1]^2)^2
  f_1<-function(x) c(2*(x[1]-1)+400*x[1]*(x[1]^2-x[2]),200*(x[2]-x[1]^2))
  delta_f1<-function(x, y){2*(x-1)+400*x*(x^2-y)}
  delta_f2<-function(x, y){200*(y-x^2)}
  
  x=x0
  alpha=alpha0
  x.values=matrix(0,itr+1,2)
  x.values[1,]=x0
  
  i=0
  for(t in 1:itr){
    x_before=x
    x=x-alpha*f_1(x)
    x.values[t+1,]=x
    
    if(f(x)>f(x_before)){
      alpha=alpha/2
    }
    
    i=i+1
    
    if(norm(alpha*c(delta_f1(x[1],x[2]),delta_f2(x[1],x[2])),type="2")<=epsilon) break
  }
  times=i
  x.values=x.values[1:(times+1),]
  return(list(x=x,x.values=x.values,times=times))
}
```
  
```{r}
#Conjugate Gradient
Conjugate<-function(x0,iter,epsilon){
  f<-function(x) (1-x[1])^2+100*(x[2]-x[1]^2)^2
  g<-function(x) c(2*(x[1]-1)+400*x[1]*(x[1]^2-x[2]),200*(x[2]-x[1]^2))
  x <- x0
  H <- diag(1, 2, 2)
  f0 <- f(x)
  g0 <- g(x)
  x.values=matrix(0,iter+1,2)
  x.values[1,]=x0
  
  for (k in 1:iter) {
    s <- - H %*% as.matrix(g0)
    f1 <- f0
    z <- sqrt(sum(s^2))
    if (z == 0){
      x.values=x.values[1:k,]
      return(list(x = x, x.values=x.values,times=k))
    }
      

    s <- c(s / z)
    a1 <- 0
    a3 <- 1; f3 <- f(x + a3*s)
    while (f3 >= f1) {
      a3 <- a3/2
      f3 <- f(x + a3*s)
      if (a3 < epsilon/2) {
        x.values=x.values[1:k,]
        return(list(x = x, x.values=x.values,times=k))
      }
    }

    a2 <- a3/2; f2 <- f(x + a2*s)
    h1 <- (f2 - f1)/a2
    h2 <- (f3 -f2)/(a3 - a2)
    h3 <- (h2 - h1)/a3
    a0 <- 0.5*(a2 - h1/h3); f0 <- f(x + a0*s)
        
    if (f0 < f3){
      a <- a0
    }
    else{
      a <- a3
    }

    d <- a * s; dp <- as.matrix(d)
    xnew <- x + d
    fnew <- f(xnew)
    gnew <- g(xnew)
    y <- gnew - g0; yp <- as.matrix(y)
    A <- (dp %*% d) / sum(d * y)
    B <- (H %*% yp) %*% t(H %*% yp) / c(y %*% H %*% yp)
    Hnew <- H + A - B
    
    x.values[k+1,]=xnew
    
    if (max(abs(d)) <= epsilon) break

    H <- Hnew
    f0 <- fnew
    g0 <- gnew
    x <- xnew
  }
  x.values=x.values[1:(k+1),]
  
  return(list(x = x, x.values=x.values,times=k))
}
```

```{r}
#Newton Result
x<-Newton(c(0.7,0),40,10^(-6))[[1]]
x.values<-Newton(c(0.7,0),40,10^(-6))[[2]]
times<-Newton(c(0.7,0),40,10^(-6))[[3]]

paste("x1=",x[1],", x2=",x[2])

#Contour plot
z = matrix(0,100,100)
x1.max = max(1.5,ceiling(max(x.values[,1])))
x1.min = min(0.5,floor(min(x.values[,1])))
x2.max = max(1.5,ceiling(max(x.values[,2])))
x2.min = min(-0.5,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:times){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```

```{r}
#Gradient Descend Result
x<-Grad(0.037,c(0,0),1000,10^(-6))[[1]]
x.values<-Grad(0.037,c(0,0),1000,10^(-6))[[2]]
times<-Grad(0.037,c(0,0),1000,10^(-6))[[3]]

paste("x1=",x[1],", x2=",x[2])

#Contour plot
z = matrix(0,100,100)
x1.max = max(1,ceiling(max(x.values[,1])))
x1.min = min(-0.5,floor(min(x.values[,1])))
x2.max = max(1,ceiling(max(x.values[,2])))
x2.min = min(-0.5,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:times){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```

```{r}
#Conjugate Gradient Result
x<-Conjugate(c(0,0),40,10^(-6))[[1]]
x.values<-Conjugate(c(0,0),40,10^(-6))[[2]]
times<-Conjugate(c(0,0),40,10^(-6))[[3]]

paste("x1=",x[1],", x2=",x[2])

#Contour plot
z = matrix(0,100,100)
x1.max = max(1,ceiling(max(x.values[,1])))
x1.min = min(-0.5,floor(min(x.values[,1])))
x2.max = max(1,ceiling(max(x.values[,2])))
x2.min = min(-0.5,floor(min(x.values[,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
     z[i,j] = f(c(x1[i],x2[j]))
  }
}
tcol<-terrain.colors(12)
contour(x1, x2, z, nlevels=20, col=tcol)
for(i in 1:(times-1)){
  segments(x.values[i,1],x.values[i,2],
           x.values[i+1,1],x.values[i+1,2],lty=2)
}
```