---
title: "QR-Decomposition Algorithms"
author: "Zihui Wang"
date: "2022-10-12"
output: 
  pdf_document: default
---

*This file includes 3 well-known QR-Decomposition Algorithms:*  
*Classical Gram-Schmidt Algorithm, Modified Gram-Schmidt Algorithm and Householder Algorithm*  
```{r}
#Classical Gram-Schmidt Algorithm
CGS<-function(x){
v<-matrix(NA,nrow=nrow(x),ncol=ncol(x))
r<-matrix(0,nrow=ncol(x),ncol=ncol(x))
q<-matrix(NA,nrow=nrow(x),ncol=ncol(x))
v[,1]<-x[,1]
r[1,1]<-sqrt(sum(v[,1]^2))
q[,1]<-v[,1]/r[1,1]
  for(j in 2:ncol(x)){
    v[,j]<-x[,j]
    for(i in 1:(j-1)){
      r[i,j]<-t(q[,i]) %*% x[,j]
      v[,j]<-v[,j]-r[i,j]*q[,i]
    }
    r[j,j]<-sqrt(sum(v[,j]^2))
    q[,j]<-v[,j]/r[j,j]
  }
return(list(Q=q,R=r))
}
```
  
```{r}
#Modified Gram-Schmidt Algorithm
MGS<-function(x){
v<-matrix(NA,nrow=nrow(x),ncol=ncol(x))
r<-matrix(0,nrow=ncol(x),ncol=ncol(x))
q<-matrix(NA,nrow=nrow(x),ncol=ncol(x))
v[,1]<-x[,1]
r[1,1]<-sqrt(sum(v[,1]^2))
q[,1]<-v[,1]/r[1,1]
  for(j in 2:ncol(x)){
    v[,j]<-x[,j]
    for(i in 1:(j-1)){
      r[i,j]<-t(q[,i]) %*% v[,j]
      v[,j]<-v[,j]-r[i,j]*q[,i]
    }
    r[j,j]<-sqrt(sum(v[,j]^2))
    q[,j]<-v[,j]/r[j,j]
  }
return(list(Q=q,R=r))
}
```
  
```{r}
#Householder Algorithm
Householder<-function(x){
  m=nrow(x)
  n=ncol(x)
  v<-matrix(NA,nrow=m,ncol=n)
  r<-matrix(0,nrow=n,ncol=n)
  q<-matrix(NA,nrow=m,ncol=n)
  w<-matrix(0,nrow=m,ncol=n)
  for(i in 1:n){
    X<-x[i:m,i]
    V<-X
    V[1]<-V[1]+(2*as.numeric(x[1]>=0)-1)*norm(X,type="2")
    V<-V/norm(V,type="2")
    x[i:m,i:n]<-x[i:m,i:n]-2*V %*% (t(V) %*% x[i:m,i:n])
    w[i:m,i]<-V
  }
  Q<-diag(m)
  for(j in 1:n){
    V<-w[j:m,j]
    q<-diag(m)
    q[j:m,j:m]<-q[j:m,j:m]-2*V %*% t(V)
    Q<-Q %*% q
  }
  return(list(Q=Q,R=x))
}
```
  
```{r}
#Test using Vandermonde matrix
set.seed(29)
Van<-matrix(NA,nrow=25,ncol=15)
for(i in 1:25){
  Van[i,1]<-1
  Van[i,2]<-runif(1)
  for(j in 3:15){
    Van[i,j]<-Van[i,2]^(j-1)
  }
}

CGS(Van)
MGS(Van)
Householder(Van)
```