---
title: "Quasi-Newton Algorithms: DFP and BFGS Updates"
author: "Zihui Wang"
date: "2022-10-12"
output: 
  pdf_document: default
---

*Codes for DFP and BFGS updates as Quasi-Newton Algorithms for optimization:*  
```{r}
#A function to be optimized
g <- function(x){((x[1]^2)+x[2]-11)^2+(x[1]+(x[2]^2)-7)^2}
g.prime <- function(x){
  g.prime.da = (4*x[1]^3)+(4*x[1]*x[2])-(42*x[1])+(2*x[2]^2)-14
  g.prime.db = (2*x[1]^2)-(26*x[2])-22+(4*x[1]*x[2])+(4*x[2]^3)
  out = matrix(c(g.prime.da,g.prime.db),ncol=1)
  return(out)
}
```
  
```{r}
#DFP Algorithm
DFP.min<-function(x,g,g.prime,epsilon,itr){
  H=diag(x=1,ncol=2,nrow=2)
  x.values = matrix(0, itr+1, 2)
  x.values[1,] = x
  alpha.default = 1
  alpha = alpha.default
  
  for(i in 1:itr){
    xt = x - alpha*H %*% g.prime(x)
    while(g(xt) > g(x)){
      alpha = alpha/2
      xt = x - alpha*H %*% g.prime(x)
    }
    x.values[i+1,] = xt
    z = xt-x
    y = g.prime(xt)-g.prime(x)
    v = z-H %*% y
    H.old = H
    H = H-((H %*% y %*% t(H %*% y))/((t(y) %*% H %*% y)[1]))+((z %*% t(z))/((t(y) %*% z)[1]))
    if(abs((t(v)%*%z)[1]) < epsilon){H = H.old}
    alpha = alpha.default
    x = xt
  }
  return(list(x=xt,gx=g(xt),xvalues=x.values))
}
```
  
```{r}
#BFGS Algorithm:
BFGS.min<-function(x,g,g.prime,epsilon,itr){
  M=diag(x=1,ncol=2,nrow=2)
  x.values = matrix(0, itr+1, 2)
  x.values[1,] = x
  alpha.default = 1
  alpha = alpha.default
  
  for(i in 1:itr){
    hessian.inv = solve(M)
    xt = x - alpha*hessian.inv %*% g.prime(x)
    while(g(xt) > g(x)){
      alpha = alpha/2
      xt = x - alpha*hessian.inv %*% g.prime(x)
    }
    x.values[i+1,] = xt
    z = xt-x
    y = g.prime(xt)-g.prime(x)
    v = y-M %*% z
    M.old = M
    M = M-((M %*% z %*% t(M %*% z))/((t(z) %*% M %*% z)[1]))+((y %*% t(y))/((t(z) %*% y)[1]))
    if(abs((t(v)%*%z)[1]) < epsilon){M = M.old}
    alpha = alpha.default
    x = xt
  }
  return(list(x=xt,gx=g(xt),xvalues=x.values))
}
```
  
```{r}
#Minimizing by DFP and its Contour Plot showing convergence:
result.DFP<-DFP.min(c(-4,0),g,g.prime,1e-10,40)
z = matrix(0,100,100)
x1.max = max(4,ceiling(max(result.DFP[[3]][,1])))
x1.min = min(0.5,floor(min(result.DFP[[3]][,1])))
x2.max = max(3,ceiling(max(result.DFP[[3]][,2])))
x2.min = min(0.5,floor(min(result.DFP[[3]][,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
    z[i,j] = g(c(x1[i],x2[j]))
  }
}
tcol <- terrain.colors(12)
contour(x1, x2, z, nlevels=20, col = tcol)

for(i in 1:40){
  segments(result.DFP[[3]][i,1],result.DFP[[3]][i,2],result.DFP[[3]][i+1,1],result.DFP[[3]][i+1,2],lty=2)
}
result.DFP
```
  
```{r}
#Minimizing by BFGS and its Contour Plot showing convergence:
result.BFGS<-BFGS.min(c(-4,0),g,g.prime,1e-10,40)
z = matrix(0,100,100)
x1.max = max(4,ceiling(max(result.BFGS[[3]][,1])))
x1.min = min(0.5,floor(min(result.BFGS[[3]][,1])))
x2.max = max(3,ceiling(max(result.BFGS[[3]][,2])))
x2.min = min(0.5,floor(min(result.BFGS[[3]][,2])))
x1 = seq(x1.min,x1.max,length=100)
x2 = seq(x2.min,x2.max,length=100)
for(i in 1:100){
  for(j in 1:100){
    z[i,j] = g(c(x1[i],x2[j]))
  }
}
tcol <- terrain.colors(12)
contour(x1, x2, z, nlevels=20, col = tcol)

for(i in 1:40){
  segments(result.BFGS[[3]][i,1],result.BFGS[[3]][i,2],result.BFGS[[3]][i+1,1],result.BFGS[[3]][i+1,2],lty=2)
}
result.BFGS
```
  

